language: python

sudo: required

services:
  - docker

python:
  - 2.7
  - 3.5

env:
  - RELEASE_ON_VER=3.5

install:
  - pip install jq yq twine

script:
  - set -e
  - make build
  - make test
  - make release